## ML lab 08: Tensor Manipulation

In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
tf.set_random_seed(777)  # for reproducibility
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### 1D Array and slicing

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])

# shape
print('dim :', t.ndim) # rank(차원)
print('shape :', t.shape) # shape(모양)

# slicing
print(t[0], t[1], t[-1]) # 0번째, 1번째, 마지막번째
print(t[2:5], t[4:-1]) # 2번째에서 4번째까지, 4번째에서 마지막-1까지
print(t[:2], t[3:]) # 처음부터 1번째까지, 3번째에서 마지막까지

dim : 1
shape : (7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


#### 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print('array :\n', t)
print('dim :', t.ndim) # rank
print('shape :', t.shape) # shape

array :
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
dim : 2
shape : (4, 3)


#### Shape, Rank, Axis

In [4]:
t = np.array([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])

print('dim :', t.ndim)
print('shape :', t.shape)

dim : 4
shape : (1, 2, 3, 4)


In [5]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

#### Matmul VS Multiply

In [6]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[3.],[2.]])

print('shape :' , tf.shape(matrix2).eval())
print('matmul :\n', tf.matmul(matrix1, matrix2).eval()) # matrix [2,2] * [2,1] = [2, 1]
print('multiply :\n', (matrix1*matrix2).eval())

shape : [2 1]
matmul :
 [[ 7.]
 [17.]]
multiply :
 [[3. 6.]
 [6. 8.]]


#### Broadcasting 

In [7]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.]])

print('broad_result :', (matrix1+matrix2).eval())

broad_result : [[5. 5.]]


#### Reduce Mean/Sum

In [8]:
x = [[1., 2.],
     [3., 4.]]


print('reduce_mean all :', tf.reduce_mean(x).eval())
print('reduce_mean axis=0 :', tf.reduce_mean(x, axis=0).eval())
print('reduce_mean axis=1 :', tf.reduce_mean(x, axis=1).eval())
print('reduce_mean axis=-1 :', tf.reduce_mean(x, axis=-1).eval())

reduce_mean all : 2.5
reduce_mean axis=0 : [2. 3.]
reduce_mean axis=1 : [1.5 3.5]
reduce_mean axis=-1 : [1.5 3.5]


#### Argmax

In [9]:
x = [[0, 1, 2],
     [2, 1, 0]]

print('argmax axis=0 :', tf.argmax(x, axis=0).eval()) # index를 반환
print('argmax axis=1 :', tf.argmax(x, axis=1).eval()) # index를 반환

argmax axis=0 : [1 0 0]
argmax axis=1 : [2 0]


#### Reshape

In [10]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])

print('shape :', t.shape) # shape
print('reshape :\n', tf.reshape(t, shape=[-1, 3]).eval()) # 차원을 축소

shape : (2, 2, 3)
reshape :
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


#### Squeeze & Expand_dims

In [11]:
print('squeeze :', tf.squeeze([[0], [1], [2]]).eval()) # 차원을 축소
print('expand_dims :\n', tf.expand_dims([0, 1, 2], 1).eval()) # 차원을 확대

squeeze : [0 1 2]
expand_dims :
 [[0]
 [1]
 [2]]


#### One hot

In [12]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
print('one_hot :\n',tf.reshape(t, shape=[-1, 3]).eval()) # 차원 축소

one_hot :
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


#### Casting

In [13]:
print('casting float to int :', tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()) # float을 int로 변환
print('casting bool to int :', tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()) # bool형태를 int로 변환

casting float to int : [1 2 3 4]
casting bool to int : [1 0 1 0]


#### Stack

In [14]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

print('exis = 0 (위아래):\n', tf.stack([x, y, z]).eval())
print('exis = 1 (옆으로):\n', tf.stack([x, y, z], axis=-1).eval())

exis = 0 (위아래):
 [[1 4]
 [2 5]
 [3 6]]
exis = 1 (옆으로):
 [[1 2 3]
 [4 5 6]]


#### Ones like & Zeros like

In [15]:
x = [[0, 1, 2],
     [2, 1, 0]]

print('ones :\n', tf.ones_like(x).eval())
print('zeros :\n', tf.zeros_like(x).eval())

ones :
 [[1 1 1]
 [1 1 1]]
zeros :
 [[0 0 0]
 [0 0 0]]


#### Zip

In [16]:
# 복수개를 동시에 실행
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


#### Transpose

In [17]:
t1 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
t2 = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]).T # transpose

print('shape :' , t1.shape)
print('matrix :\n', t1)
print('shape :' , t2.shape)
print('transpose :\n', t2)

shape : (2, 2, 3)
matrix :
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
shape : (3, 2, 2)
transpose :
 [[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]
