## ML lab 06-1: TensorFlow로 Softmax Classification의 구현하기

In [1]:
import tensorflow as tf

# training data
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], 
          [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
# one-hot encoding
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# input data
X = tf.placeholder(tf.float32, shape = [None, 4])
Y = tf.placeholder(tf.float32, shape = [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

# hypothesis
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b) # (H(x))

# cost/loss function (cross entropy)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

# optimizer
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# launch
with tf.Session() as sess : 
    
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000+1) :
        sess.run(optimizer, feed_dict = {X : x_data, Y : y_data})
        if step % 200 == 0 :
            print(step, sess.run(cost, feed_dict = {X : x_data, Y : y_data}))
            
    
    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 2.6197848
200 0.69944704
400 0.57564825
600 0.48888573
800 0.4153633
1000 0.34665823
1200 0.27610996
1400 0.23136179
1600 0.2106674
1800 0.19319314
2000 0.17826223
--------------
[[8.735208e-02 9.126382e-01 9.684783e-06]] [1]
--------------
[[0.5531862  0.41507465 0.03173912]] [0]
--------------
[[3.7727325e-08 4.9282896e-04 9.9950707e-01]] [2]
--------------
[[8.7352082e-02 9.1263819e-01 9.6847834e-06]
 [5.5318618e-01 4.1507468e-01 3.1739116e-02]
 [3.7727325e-08 4.9282896e-04 9.9950707e-01]] [1 0 2]
